theme: jekyll-theme-minimal
title: Retail Inventory Management System
description: Comprehensive retail inventory management system with Java Spring Boot backend, MySQL database, and Excel VBA integration.
